---
repos:
  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.2.0
    hooks:
      - id: bolt-validate
      - id: epp-validate
      - id: erb-validate
      - id: puppet-lint
        args: [
          "--fail-on-warnings",
        ]
      - id: puppet-validate
      - id: r10k-validate
      - id: ruby-validate
        args: [
          "--no-80chars-check",
          "--no-documentation-check",
          "--no-puppet_url_without_modules-check"
        ]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: reek
      - id: rubocop

  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.27.1
    hooks:
      - id: 'yamllint'
